services :
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - webserver:/var/www/html/
    networks:
      - frontend
    depends_on:
      - "wordpress"
  wordpress:
    tty: true
    build: requirements/wordpress/
    container_name: wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - webserver:/var/www/html
    networks:
      - frontend
      - backend
    depends_on:
      - "mariadb"
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql:/var/lib/mysql/
    networks:
      - backend
volumes:
  webserver:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/robrodri/data/webserver'
  mysql:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/robrodri/data/mysql'
networks:
  frontend:
  backend:
